<?php
/*
 * LaraClassifier - Classified Ads Web Application
 * Copyright (c) BeDigit. All Rights Reserved
 *
 * Website: https://laraclassifier.com
 * Author: Mayeul Akpovi (BeDigit - https://bedigit.com)
 *
 * LICENSE
 * -------
 * This software is provided under a license agreement and may only be used or copied
 * in accordance with its terms, including the inclusion of the above copyright notice.
 * As this software is sold exclusively on CodeCanyon,
 * please review the full license details here: https://codecanyon.net/licenses/standard
 */

namespace App\Http\Controllers\Api\Auth;

use App\Http\Controllers\Api\Auth\Traits\VerificationTrait;
use App\Http\Controllers\Api\BaseController;
use App\Http\Requests\Front\ForgotPasswordRequest;
use App\Http\Controllers\Api\Auth\Helpers\SendsPasswordResetEmails;
use App\Http\Controllers\Api\Auth\Helpers\SendsPasswordResetSms;

/**
 * @group Authentication
 */
class ForgotPasswordController extends BaseController
{
    use SendsPasswordResetEmails, SendsPasswordResetSms;
	use VerificationTrait;
    
    /**
     * Forgot password
	 *
	 * @bodyParam auth_field string required The user's auth field ('email' or 'phone'). Example: email
	 * @bodyParam email string The user's email address or username (Required when 'auth_field' value is 'email'). Example: user@demosite.com
	 * @bodyParam phone string The user's mobile phone number (Required when 'auth_field' value is 'phone'). Example: null
	 * @bodyParam phone_country string required The user's phone number's country code (Required when the 'phone' field is filled). Example: null
	 * @bodyParam captcha_key string Key generated by the CAPTCHA endpoint calling (Required when the CAPTCHA verification is enabled from the Admin panel).
     *
	 * @param \App\Http\Requests\Front\ForgotPasswordRequest $request
	 * @return \Illuminate\Http\JsonResponse
	 */
    public function sendResetLink(ForgotPasswordRequest $request): \Illuminate\Http\JsonResponse
	{
		// Get the right auth field
		$authField = getAuthField();
        
        // Send the Token by SMS
        if ($authField == 'phone') {
            return $this->sendResetTokenSms($request);
        }
        
        // Go to the core process
		try {
			$jsonResponse = $this->sendResetLinkEmail($request);
		} catch (\Throwable $e) {
			return apiResponse()->error(getExceptionMessage($e));
		}
		
		return $jsonResponse;
    }
}
